-- Depósitos / almacenes y tiendas por cuenta de cliente.
-- Se aplica a mano porque el esquema vivo se creó con EnsureCreated() y no sigue
-- el historial de migraciones de EF Core.
--
--   psql -h localhost -p 5432 -U postgres -d InventoryDb -f 001_AddAccountLocations.sql

CREATE TABLE IF NOT EXISTS "AccountLocations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerAccountId" integer NOT NULL,
    "Name" text NOT NULL,
    "Type" integer NOT NULL,
    "Address" text NOT NULL,
    "Rif" text NOT NULL,
    "Phone" text NOT NULL,
    CONSTRAINT "PK_AccountLocations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountLocations_CustomerAccounts_CustomerAccountId"
        FOREIGN KEY ("CustomerAccountId") REFERENCES "CustomerAccounts" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AccountLocations_CustomerAccountId_Name"
    ON "AccountLocations" ("CustomerAccountId", "Name");
