-- ---------------------------------------------------------------------------
-- Facturación fiscal: cajas (Terminals), rangos de numeración y facturas.
--
-- POR QUÉ ESTE ARCHIVO EXISTE Y NO SE APLICA UNA MIGRACIÓN:
-- La base viva se creó con EnsureCreated, no con migraciones, así que su
-- historial de EF no coincide con las tablas que realmente tiene. Generar el
-- script con `dotnet ef migrations script` produce CREATE TABLE para tablas que
-- ya existen (AccountLocations, AccountLogos, ItemStocks) y falla a mitad de
-- camino. Este archivo contiene ÚNICAMENTE los objetos nuevos de facturación,
-- con guardas IF NOT EXISTS, para aplicarlo a mano:
--
--     psql -h <host> -U <usuario> -d <base> -f Inventory.API/Sql/001_invoicing.sql
--
-- Es idempotente: correrlo dos veces no hace daño.
-- ---------------------------------------------------------------------------

BEGIN;

-- Cajas / puntos de venta ----------------------------------------------------
CREATE TABLE IF NOT EXISTS "Terminals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerAccountId" integer NOT NULL,
    "StoreId" integer,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    "Serie" text NOT NULL,
    "DeviceIdentifier" text,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Terminals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Terminals_AccountLocations_StoreId" FOREIGN KEY ("StoreId")
        REFERENCES "AccountLocations" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Terminals_CustomerAccounts_CustomerAccountId" FOREIGN KEY ("CustomerAccountId")
        REFERENCES "CustomerAccounts" ("Id") ON DELETE RESTRICT
);

-- Dos cajas de la misma cuenta no pueden compartir código ni serie: compartir
-- serie es exactamente lo que rompería la unicidad del correlativo.
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Terminals_CustomerAccountId_Code"
    ON "Terminals" ("CustomerAccountId", "Code");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Terminals_CustomerAccountId_Serie"
    ON "Terminals" ("CustomerAccountId", "Serie");
CREATE INDEX IF NOT EXISTS "IX_Terminals_StoreId"
    ON "Terminals" ("StoreId");

-- Rangos de numeración reservados por adelantado ------------------------------
CREATE TABLE IF NOT EXISTS "InvoiceNumberRanges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TerminalId" integer NOT NULL,
    "DocumentType" integer NOT NULL,
    "Serie" text NOT NULL,
    "FromNumber" bigint NOT NULL,
    "ToNumber" bigint NOT NULL,
    "NextNumber" bigint NOT NULL,
    "ControlPrefix" text NOT NULL,
    "ControlFromNumber" bigint NOT NULL,
    "Status" integer NOT NULL,
    "AssignedAtUtc" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "Authorization" text,
    CONSTRAINT "PK_InvoiceNumberRanges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceNumberRanges_Terminals_TerminalId" FOREIGN KEY ("TerminalId")
        REFERENCES "Terminals" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_InvoiceNumberRanges_TerminalId_DocumentType_FromNumber"
    ON "InvoiceNumberRanges" ("TerminalId", "DocumentType", "FromNumber");

-- Facturas --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Invoices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientGuid" uuid NOT NULL,
    "DocumentType" integer NOT NULL,
    "Status" integer NOT NULL,
    "Serie" text NOT NULL,
    "Number" bigint NOT NULL,
    "ControlNumber" text NOT NULL,
    "TerminalId" integer NOT NULL,
    "InvoiceNumberRangeId" integer,
    "IssuedAt" timestamp with time zone NOT NULL,
    "ReceivedAtUtc" timestamp with time zone NOT NULL,
    "CustomerAccountId" integer NOT NULL,
    "StoreId" integer,
    "WarehouseId" integer,
    "CreatedByUserId" integer NOT NULL,
    "ConsumerCustomerId" integer,
    "CustomerName" text NOT NULL,
    "CustomerDocument" text NOT NULL,
    "CustomerAddress" text NOT NULL,
    "CustomerPhone" text NOT NULL,
    "CurrencyId" integer,
    "ExchangeRate" numeric,
    "Subtotal" numeric NOT NULL,
    "TotalTax" numeric NOT NULL,
    "Total" numeric NOT NULL,
    "Notes" text NOT NULL,
    "ReferenceInvoiceId" integer,
    "VoidedAtUtc" timestamp with time zone,
    "VoidReason" text,
    CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Invoices_AccountLocations_StoreId" FOREIGN KEY ("StoreId")
        REFERENCES "AccountLocations" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_AccountLocations_WarehouseId" FOREIGN KEY ("WarehouseId")
        REFERENCES "AccountLocations" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_ConsumerCustomers_ConsumerCustomerId" FOREIGN KEY ("ConsumerCustomerId")
        REFERENCES "ConsumerCustomers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId")
        REFERENCES "Currencies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_CustomerAccountUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId")
        REFERENCES "CustomerAccountUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_CustomerAccounts_CustomerAccountId" FOREIGN KEY ("CustomerAccountId")
        REFERENCES "CustomerAccounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_InvoiceNumberRanges_InvoiceNumberRangeId" FOREIGN KEY ("InvoiceNumberRangeId")
        REFERENCES "InvoiceNumberRanges" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_Invoices_ReferenceInvoiceId" FOREIGN KEY ("ReferenceInvoiceId")
        REFERENCES "Invoices" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invoices_Terminals_TerminalId" FOREIGN KEY ("TerminalId")
        REFERENCES "Terminals" ("Id") ON DELETE RESTRICT
);

-- Estas dos son las garantías duras del esquema offline:
--   * ClientGuid único  -> el reintento del POS nunca duplica una factura.
--   * serie+número único -> aunque una caja se equivoque o se restaure un
--     respaldo viejo, la base rechaza un correlativo repetido.
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invoices_ClientGuid"
    ON "Invoices" ("ClientGuid");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invoices_CustomerAccountId_DocumentType_Serie_Number"
    ON "Invoices" ("CustomerAccountId", "DocumentType", "Serie", "Number");

CREATE INDEX IF NOT EXISTS "IX_Invoices_ConsumerCustomerId" ON "Invoices" ("ConsumerCustomerId");
CREATE INDEX IF NOT EXISTS "IX_Invoices_CreatedByUserId" ON "Invoices" ("CreatedByUserId");
CREATE INDEX IF NOT EXISTS "IX_Invoices_CurrencyId" ON "Invoices" ("CurrencyId");
CREATE INDEX IF NOT EXISTS "IX_Invoices_InvoiceNumberRangeId" ON "Invoices" ("InvoiceNumberRangeId");
CREATE INDEX IF NOT EXISTS "IX_Invoices_ReferenceInvoiceId" ON "Invoices" ("ReferenceInvoiceId");
CREATE INDEX IF NOT EXISTS "IX_Invoices_StoreId" ON "Invoices" ("StoreId");
CREATE INDEX IF NOT EXISTS "IX_Invoices_TerminalId" ON "Invoices" ("TerminalId");
CREATE INDEX IF NOT EXISTS "IX_Invoices_WarehouseId" ON "Invoices" ("WarehouseId");

-- Líneas ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "InvoiceLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" integer NOT NULL,
    "ItemUniversalId" integer,
    "CategoryId" integer,
    "CurrencyId" integer,
    "Code" text NOT NULL,
    "Description" text NOT NULL,
    "Quantity" numeric NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "TaxRate" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "ExchangeRate" numeric,
    CONSTRAINT "PK_InvoiceLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceLines_Categories_CategoryId" FOREIGN KEY ("CategoryId")
        REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InvoiceLines_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId")
        REFERENCES "Currencies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InvoiceLines_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId")
        REFERENCES "Invoices" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InvoiceLines_Items_ItemUniversalId" FOREIGN KEY ("ItemUniversalId")
        REFERENCES "Items" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_InvoiceLines_CategoryId" ON "InvoiceLines" ("CategoryId");
CREATE INDEX IF NOT EXISTS "IX_InvoiceLines_CurrencyId" ON "InvoiceLines" ("CurrencyId");
CREATE INDEX IF NOT EXISTS "IX_InvoiceLines_InvoiceId" ON "InvoiceLines" ("InvoiceId");
CREATE INDEX IF NOT EXISTS "IX_InvoiceLines_ItemUniversalId" ON "InvoiceLines" ("ItemUniversalId");

-- ---------------------------------------------------------------------------
-- Marca la migración AddInvoicing como aplicada para que EF no intente correr su
-- Up(), que fallaría: esa migración incluye CREATE TABLE de AccountLocations,
-- AccountLogos e ItemStocks, tablas que la base ya tiene desde EnsureCreated.
--
-- OJO: esto sólo cubre AddInvoicing. Si las migraciones anteriores tampoco están
-- registradas en el historial, Program.cs las seguirá viendo pendientes y seguirá
-- cayendo a EnsureCreated en cada arranque (inofensivo: en una base que ya existe
-- no hace nada). Verifícalo con:
--     SELECT "MigrationId" FROM "__EFMigrationsHistory" ORDER BY 1;
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260828010223_AddInvoicing', '9.0.17')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
